services:
  web:
    image: php:8.2-apache
    container_name: cfk-web
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./logs:/var/www/html/logs
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      # Production-like PHP settings
      - PHP_MEMORY_LIMIT=256M
      - PHP_MAX_EXECUTION_TIME=300
      - PHP_UPLOAD_MAX_FILESIZE=50M
      - PHP_POST_MAX_SIZE=50M
      - PHP_DISPLAY_ERRORS=Off
      - PHP_LOG_ERRORS=On
    depends_on:
      - db
    command: >
      bash -c "
        docker-php-ext-install pdo pdo_mysql mysqli &&
        docker-php-ext-enable opcache &&
        a2enmod rewrite &&
        echo 'ServerName localhost' >> /etc/apache2/apache2.conf &&
        mkdir -p /var/www/html/logs &&
        chown -R www-data:www-data /var/www/html/logs &&
        apache2-foreground
      "

  db:
    image: mysql:8.0
    container_name: cfk-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cfk_sponsorship_dev
      MYSQL_USER: cfk_user
      MYSQL_PASSWORD: cfk_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cfk-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  mysql_data: