<?php
/**
 * Sample Data Generator for Staging
 * Generates realistic test data for children and families
 *
 * Usage: php database/sample-data-generator.php [number_of_children]
 */

define('CFK_APP', true);

require_once __DIR__ . '/../vendor/autoload.php';
require_once __DIR__ . '/../config/config.php';

// Number of children to generate
$count = (int)($argv[1] ?? 200);

echo "🎄 Sample Data Generator\n";
echo "========================\n";
echo "Generating $count sample children...\n\n";

// Sample data arrays
$boyFirstNames = [
    'James', 'Michael', 'David', 'John', 'Robert', 'William', 'Christopher', 'Daniel', 'Matthew', 'Joseph',
    'Anthony', 'Joshua', 'Andrew', 'Brian', 'Kevin', 'Thomas', 'Ryan', 'Jacob', 'Nicholas', 'Tyler',
    'Ethan', 'Noah', 'Liam', 'Mason', 'Logan', 'Lucas', 'Alexander', 'Benjamin', 'Samuel', 'Nathan'
];

$girlFirstNames = [
    'Mary', 'Jennifer', 'Lisa', 'Michelle', 'Jessica', 'Ashley', 'Sarah', 'Amanda', 'Melissa', 'Nicole',
    'Emily', 'Emma', 'Olivia', 'Sophia', 'Isabella', 'Mia', 'Charlotte', 'Amelia', 'Harper', 'Evelyn',
    'Abigail', 'Elizabeth', 'Sofia', 'Avery', 'Ella', 'Madison', 'Scarlett', 'Grace', 'Chloe', 'Victoria'
];

$interests = [
    'Art, drawing, painting',
    'Sports, soccer, basketball',
    'Reading, books, stories',
    'Music, singing, dancing',
    'Video games, computers',
    'Animals, pets, nature',
    'Science, experiments',
    'Legos, building blocks',
    'Dolls, dress-up',
    'Puzzles, board games',
    'Cooking, baking',
    'Outdoor activities, hiking',
    'Crafts, DIY projects',
    'Cars, trucks, trains',
    'Dinosaurs, fossils',
    'Space, astronomy',
    'Superheroes, comics',
    'Princess stories, fairy tales',
    'Swimming, water activities',
    'Bikes, scooters, skating'
];

$wishes = [
    'Art supplies and coloring books',
    'Sports equipment and balls',
    'Chapter books and reading material',
    'Musical instruments or music toys',
    'Age-appropriate video games',
    'Stuffed animals and pet toys',
    'Science kits and experiments',
    'Lego sets and building toys',
    'Dolls and accessories',
    'Board games and puzzles',
    'Baking set and play kitchen',
    'Outdoor toys and sports gear',
    'Craft supplies and DIY kits',
    'Toy vehicles and tracks',
    'Dinosaur toys and books',
    'Space toys and planetarium',
    'Superhero action figures',
    'Princess dolls and dress-up clothes',
    'Swimming gear and water toys',
    'Bike accessories and safety gear'
];

$shirtSizes = ['XS', 'S', 'M', 'L', 'XL'];
$pantSizes = ['4', '5', '6', '7', '8', '10', '12', '14', '16'];
$shoeSizes = ['10', '11', '12', '13', '1', '2', '3', '4', '5', '6', '7'];
$jacketSizes = ['XS', 'S', 'M', 'L', 'XL'];

// Grades mapping by age
$gradesByAge = [
    0 => 'Infant',
    1 => 'Infant',
    2 => 'Toddler',
    3 => 'Pre-K',
    4 => 'Pre-K',
    5 => 'Kindergarten',
    6 => '1st',
    7 => '2nd',
    8 => '3rd',
    9 => '4th',
    10 => '5th',
    11 => '6th',
    12 => '7th',
    13 => '8th',
    14 => '9th',
    15 => '10th',
    16 => '11th',
    17 => '12th',
    18 => '12th'
];

// Start with family number 200 (after existing test families)
$startingFamilyNumber = 200;
$familiesCreated = 0;
$childrenCreated = 0;

// Average 2-3 children per family
$familyCount = (int)ceil($count / 2.5);

echo "Creating ~$familyCount families...\n";

for ($f = 0; $f < $familyCount; $f++) {
    $familyNumber = $startingFamilyNumber + $f;

    // Create family
    try {
        $familyId = \CFK\Database\Connection::insert('families', [
            'family_number' => (string)$familyNumber,
            'notes' => 'Sample family for testing - generated by sample-data-generator.php'
        ]);
        $familiesCreated++;
    } catch (Exception $e) {
        echo "⚠️  Family $familyNumber already exists, skipping...\n";
        continue;
    }

    // Random number of children (1-4)
    $childCount = rand(1, 4);

    for ($c = 0; $c < $childCount && $childrenCreated < $count; $c++) {
        $childLetter = chr(65 + $c); // A, B, C, D

        // Random age (0-18 years)
        $ageYears = rand(0, 18);
        $ageMonths = $ageYears * 12;

        // Random gender
        $gender = rand(0, 1) ? 'M' : 'F';

        // Pick random name
        $firstName = $gender === 'M'
            ? $boyFirstNames[array_rand($boyFirstNames)]
            : $girlFirstNames[array_rand($girlFirstNames)];

        // Grade based on age
        $grade = $gradesByAge[$ageYears] ?? '12th';

        // Status (90% available, 10% sponsored)
        $status = rand(1, 10) <= 9 ? 'available' : 'sponsored';

        // Random interests and wishes
        $interest = $interests[array_rand($interests)];
        $wish = $wishes[array_rand($wishes)];

        // Random clothing sizes
        $shirtSize = $shirtSizes[array_rand($shirtSizes)];
        $pantSize = $pantSizes[array_rand($pantSizes)];
        $shoeSize = $shoeSizes[array_rand($shoeSizes)];
        $jacketSize = $jacketSizes[array_rand($jacketSizes)];

        try {
            \CFK\Database\Connection::insert('children', [
                'family_id' => $familyId,
                'child_letter' => $childLetter,
                'name' => $firstName,
                'age' => $ageYears,
                'age_months' => $ageMonths,
                'grade' => $grade,
                'gender' => $gender,
                'shirt_size' => $shirtSize,
                'pant_size' => $pantSize,
                'shoe_size' => $shoeSize,
                'jacket_size' => $jacketSize,
                'interests' => $interest,
                'wishes' => $wish,
                'status' => $status,
                'priority_level' => 'normal'
            ]);

            $childrenCreated++;

            if ($childrenCreated % 50 === 0) {
                echo "✓ Created $childrenCreated children...\n";
            }
        } catch (Exception $e) {
            echo "✗ Error creating child $familyNumber$childLetter: " . $e->getMessage() . "\n";
        }
    }
}

echo "\n";
echo "========================\n";
echo "✅ Sample Data Created!\n";
echo "========================\n";
echo "Families: $familiesCreated\n";
echo "Children: $childrenCreated\n";
echo "\n";

// Get statistics
$stats = \CFK\Database\Connection::fetchRow("
    SELECT
        COUNT(*) as total_children,
        SUM(CASE WHEN status = 'available' THEN 1 ELSE 0 END) as available,
        SUM(CASE WHEN status = 'sponsored' THEN 1 ELSE 0 END) as sponsored,
        SUM(CASE WHEN gender = 'M' THEN 1 ELSE 0 END) as boys,
        SUM(CASE WHEN gender = 'F' THEN 1 ELSE 0 END) as girls,
        MIN(age_months) as youngest_months,
        MAX(age_months) as oldest_months
    FROM children
");

echo "Database Statistics:\n";
echo "-------------------\n";
echo "Total children: {$stats['total_children']}\n";
echo "Available: {$stats['available']}\n";
echo "Sponsored: {$stats['sponsored']}\n";
echo "Boys: {$stats['boys']}\n";
echo "Girls: {$stats['girls']}\n";
echo "Age range: " . floor($stats['youngest_months']/12) . "-" . floor($stats['oldest_months']/12) . " years\n";
echo "\n";

echo "Test URLs:\n";
echo "----------\n";
echo "Browse all: https://10ce79bd48.nxcli.io/?page=children\n";
echo "Page 2: https://10ce79bd48.nxcli.io/?page=children&p=2\n";
echo "24 per page: https://10ce79bd48.nxcli.io/?page=children&per_page=24\n";
echo "48 per page: https://10ce79bd48.nxcli.io/?page=children&per_page=48\n";
echo "\n";

echo "✓ Complete!\n";
